# Generated by Django 4.2.10 on 2025-08-24 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_content'),
        ('notifications', '0002_notification_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='message_ar',
        ),
        migrations.AddField(
            model_name='notification',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='books.book'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
