# Generated by Django 4.2.10 on 2025-08-24 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0007_chapter_note'),
        ('notifications', '0003_rename_message_notification_message_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chapters.chapter'),
        ),
    ]
