# Generated by Django 4.2.10 on 2025-06-10 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accept', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=250)),
                ('content_text', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('note', models.CharField(max_length=250, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='books.book')),
            ],
            options={
                'db_table': 'chapters',
            },
        ),
    ]
