# Generated by Django 4.2.10 on 2025-04-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_fav_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
