# Generated by Django 4.2.10 on 2025-08-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.BooleanField(null=True),
        ),
    ]
