# Generated by Django 4.2.10 on 2025-08-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_reader',
            field=models.BooleanField(null=True),
        ),
    ]
