# Generated by Django 4.2.10 on 2025-04-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0003_reply_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply',
            new_name='content',
        ),
    ]
